### PR TITLE
Login page/customer form edits

### PR DESCRIPTION
**Pull request by Fawlty22**
I kinda did a lot here. 
I reworked the login page and customer form to match styling. But the functionality is still not there.

I should have made a new branch for this second part, but did it without realizing. 
I made the User Management section where you can search by email for customers and bring up their info.  You can then edit and resubmit their info.  That whole page works just fine.

### CODE REVIEW

**Comment by Fawlty22** [comment]
Screen Shot 2022-02-20 at 4 53 32 PM

**Comment by Fawlty22** [comment]
Screen Shot 2022-02-20 at 4 54 28 PM

**Comment by Fawlty22** [comment]
Screen Shot 2022-02-20 at 4 55 13 PM

**Review by CBranagan — DISMISSED** [review]

**Comment by Thesselonian** [comment]
great job

**Review by Thesselonian — APPROVED** [review]
great job

**Comment by Fawlty22** [comment]
Thanks guy!

**Pull request merged**
